on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: |
          git config user.name ${{ secrets.NAME }}
          git config user.email ${{ secrets.EMAIL }}
          npm i -g pnpm
          pnpm install
          pnpm --filter "remnote-plugin-*" build
          git add .
          git commit -m "build" && git push
          echo "success"
